//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dialogs_basic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class botTable
    {
        public string Name { get; set; }
        public string Place { get; set; }
        public string Price { get; set; }
        public string PhotoURL { get; set; }
        public string CardURL { get; set; }
    }
}
